### ISSUE TITLE
Update Discordeno

### ISSUE THREAD

**Issue by sebakocz** [FinlayDaG33k/deno-lib#8]
The Discordeno library has undergone a major update from version 13.0.0 to 18.0.0. To ensure compatibility and benefit from the latest features and improvements, we need to update all occurrences of discordeno@13.0.0 to discordeno@18.0.0 in the Chomp codebase. Additionally, we need to address any potential issues or errors that may arise post-update.

**Acceptance Criteria:**
- All occurrences of `discordeno@13.0.0` in Chomp have been successfully updated to `discordeno@18.0.0`.
- Chomp functions correctly without any major issues after the Discordeno version update.

**Comment by FinlayDaG33k** [comment]
Feel free to open a PR.

**Comment by sebakocz** [comment]
PR: https://github.com/FinlayDaG33k/chomp/pull/9
